# Generated by Django 2.2.6 on 2019-11-28 19:18

import account.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191124_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fllwd_users',
            field=models.ManyToManyField(related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='fllwrs',
            field=models.ManyToManyField(related_name='_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='banner_picture',
            field=models.ImageField(blank=True, default='default_images/default_banner.png', upload_to=account.models.upload_banner_location),
        ),
    ]
