# Generated by Django 2.2.6 on 2019-11-24 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPost',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to=media.models.upload_location)),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='date posted')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
