# Generated by Django 2.2.6 on 2019-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191101_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='banner_picture',
            field=models.ImageField(blank=True, upload_to='media_files/banner_pictures'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media_files/profile_pictures'),
        ),
    ]
