# Generated by Django 2.2.6 on 2019-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191102_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('E', 'Something else')], max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='residency',
            field=models.CharField(blank=True, max_length=85),
        ),
        migrations.AlterField(
            model_name='account',
            name='banner_picture',
            field=models.ImageField(blank=True, upload_to='banner_pictures'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
