# Generated by Django 2.2.6 on 2019-11-29 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191128_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='fllwd_users',
        ),
        migrations.RemoveField(
            model_name='account',
            name='fllwrs',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
